name: flutter_portfolio
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  fluentui_icons: ^1.0.0
  get: ^4.6.5
  gap: ^2.0.0
  barcode_widget: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/spotify/
    - assets/images/call/
    - assets/images/flight_booking/
    - assets/images/bookmark/
    - assets/images/registration/
    - assets/images/cars/
    - assets/images/book_ticket/
    - assets/images/chatgpt/
    - assets/images/delivery/
    - assets/project_images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Medium.ttf

