int currentTicketIndex = 0;
List<Map<String, dynamic>> ticketList = [
  {
    'fromCode': 'MCO',
    'fromName': 'Orlando',
    'toCode': 'ATL',
    'toName': 'Atlanta',
    'flyingTime': '1h 30m',
    'date': 'May 11, 8:45 am',
    'number': "F12423",
    "boardingTime": "8:00 am EST",
    "zone": "A",
    "seat": "34A",
    "class": "Bussiness",
  },
  {
    'fromCode': 'ATL',
    'fromName': 'Atlanta',
    'toCode': 'LAX',
    'toName': 'Los Angeles',
    'flyingTime': '4h 29m',
    'date': 'June 12, 12:20 pm',
    'number': "F12423",
    "boardingTime": "8:00 am EST",
    "zone": "B",
    "seat": "14B",
    "class": "Bussiness",
  },
  {
    'fromCode': 'TASH',
    'fromName': 'Tashkent',
    'toCode': 'MCW',
    'toName': 'Moscow',
    'flyingTime': '2h 30m',
    'date': 'July 5, 00:00 pm',
    'number': "F12423",
    "boardingTime": "8:00 am EST",
    "zone": "C",
    "seat": "7C",
    "class": "Bussiness",
  },
  {
    'fromCode': 'NYC',
    'fromName': 'New-York',
    'toCode': 'LDN',
    'toName': 'London',
    'flyingTime': '8h 30m',
    'date': 'Juny 16, 11:00 am',
    'number': "F12425",
    "boardingTime": "8:00 am EST",
    "zone": "D",
    "seat": "30A",
    "class": "Bussiness",
  },
];
